- .gitignore
- package-lock.json
- package.json
- src/App.jsx
- src/main.jsx
- src/supabase.js
- vite.config.js
#1 
<br/>
supabase 연동 및 데이터 조회
<br/>
> [FEAT] supabase 연동

- index.html
- src/styles/color.js
closes #6 
<br/>
CSS리셋 및 색상 상수 코드 작성
> [CHORE] CSS 리셋

- src/App.jsx
- src/components/common/Layouts/container.jsx
- src/styles/color.js
#7 
<br/>
- layouts 컴포넌트 추가.
- colors에 배경색 추가.
<br/>
> [FEAT] layouts 컴포넌트 추가

- package-lock.json
- package.json
- src/components/common/Layouts/container.jsx
close #11 
<br/>
react-router-dom 라이브러리 설치
<br/>
> [FEAT] 라우터 라이브러리 설치

- src/App.jsx
- src/components/common/Button.jsx
> [FEAT] Button 컴포넌트 추가

- src/components/common/Layouts/container.jsx
- src/pages/ResultPage.jsx
#15 
<br/>
- 패딩값에 따라 늘어난 width 수정 및 절취선 추가
<br/>
> [STYLE] 결과페이지 전체 틀 수정

- src/App.jsx
- src/components/common/results/Keyword.jsx
- src/components/common/results/KeywordDetail.jsx
- src/components/common/results/KeywordList.jsx
- src/pages/ResultPage.jsx
- src/styles/color.js
> #21 
<br/>
- 키워드 나열 및 세부사항 추가
<br/>
<br/>
> [STYLE] 키워드 나열 및 세부사항

- src/App.jsx
- src/components/QuestionPage/ChoiceButtons.jsx
- src/components/QuestionPage/QuestionContent.jsx
- src/components/common/Button.jsx
- src/pages/QuestionPage.jsx
- src/styles/color.js
> #19 
<br/>
- 질문페이지 다이나믹 라우팅
- UI 레이아웃
- QuestionContent, ChoiceButtons 컴포넌트화
<br/>
> [FEAT] 질문 페이지

- src/components/common/Layouts/container.jsx
> ex) #25 
<br/>
- 화면을 확대할 때 하단 영역의 레이아웃이 깨지는 문제 해결
> [FIX] 하단 영역 오류 수정

- src/components/common/Layouts/container.jsx
- src/pages/QuestionPage.jsx
- src/pages/ResultPage.jsx
>#32
<br/>
- 화면 잘리는 이슈에 따른 스크롤 기능 추가
> [REFACTOR] 화면에 비율에 맞게 스크롤 기능 추가

- src/components/common/results/Keyword.jsx
- src/pages/ResultPage.jsx
#34 
<br/>
데이터베이스에서 결과 가져와서 반영
<br/>
> [FEAT] 데이터베이스로부터 결과 가져오기

- src/pages/Home.jsx
#35
#35 
<br/>
- 홈 화면에서 title의 위치가 고정되지 않는 문제 해결
<br/>
> fix: home title 위치 수정

- src/components/QuestionPage/ChoiceButtons.jsx
- src/components/QuestionPage/QuestionContent.jsx
- src/components/home/HomeButton.jsx
- src/pages/Home.jsx
> #19 
<br/>
- 질문 페이지에 들어가는 컴포넌트 스타일 수정
- 기타 오타 수정
- 홈 버튼 데이터문 일부 수정
> [FIX] 질문 페이지 스타일 수정 등

- src/components/common/results/Keyword.jsx
- src/components/common/results/KeywordDetail.jsx
- src/components/common/results/KeywordList.jsx
- src/pages/ResultPage.jsx
> close #41 
<br/>
- 데이터베이스로부터 정보를 받아와 결과 페이지에 반영
<br/>
<br/>
> [FEAT] 결과 페이지에서 데이터베이스 정보 반영

- src/components/QuestionPage/ChoiceButtons.jsx
- src/components/QuestionPage/QuestionContent.jsx
- src/components/home/HomeButton.jsx
- src/pages/QuestionPage.jsx
> #39 
<br/>
- supabase 연동 및 구상
<br/>
> [FEAT] QuestionPage 컴포넌트의 기능과 스타일링 개선

- src/pages/ResultPage.jsx
- src/styles/color.js
> ex) closes #45 
<br/>
- 사용자 선택에 따른 결과 페이지 출력
<br/>
> [FEAT] 결과 페이지에서 답변 조합에 따른 결과 ID 매핑 수정

- src/pages/ResultPage.jsx
> #49 
<br/>
- 로딩 상태 시 로딩 오버레이 추가
> [FEAT] 결과 페이지 로딩 상태 관리 개선 및 로딩 오버레이 추가

- src/pages/QuestionPage.jsx
- src/pages/ResultPage.jsx
> ex) close #49 
<br/>
- 결과페이지에서 로딩이 이루어지던 것에서 질문페이지의 마지막 질문 화면에서 로딩이 이루어지는 것으로 변경
> feat: 질문 페이지에서 로딩 상태 관리 및 사전 로딩 기능 추가

- src/components/QuestionPage/QuestionContent.jsx
- src/components/common/Button.jsx
- src/components/home/HomeButton.jsx
- src/pages/Home.jsx
- src/pages/QuestionPage.jsx
#52 
<br/>
-  모바일 화면에서의 홈 화면 및 질문 화면 위치 조정
<br/>
> fix: 모바일 화면에서의 위치 조정

- index.html
- src/fonts/font.css
> [FIX] 모바일에서 폰트 적용 안되는 css 수정

- src/components/QuestionPage/QuestionContent.jsx
- src/components/common/Button.jsx
- src/components/home/HomeButton.jsx
- src/pages/Home.jsx
- src/pages/QuestionPage.jsx
#52 
<br/>
- 홈 화면, 질문 화면의 텍스트 위치 조정
- 신사 번호 변경
<br/>
> fix: 텍스트 위치 조정

- src/pages/QuestionPage.jsx
#52 
<br/>
- 화면 길이 지정문 삭제
<br/>
> fix: 화면 길이 지정문 삭제

- src/components/QuestionPage/QuestionContent.jsx
- src/pages/QuestionPage.jsx
#52 
<br/>
- 진짜 마지막 텍스트 너비 수정
<br/>
> fix: 최종 위치 수정

- src/pages/QuestionPage.jsx
> #55 
<br/>
- BackgroundImg 컴포넌트를 올바른 위치로 이동
> [FIX] BackgroundImg 컴포넌트를 QuestionPage에서 올바른 위치로 이동
